[package]
name = "psce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "3.0.12"
regex = "1.5.6"
tabled = "0.7.0"
